apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_geoconnections"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres-geoconnections"
  DB_PORT: "5432"
  KAFKA_URL: my-release-kafka.default.svc.cluster.local
  KAFKA_TOPIC: test
metadata:
  name: config-location-processor-map