apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-person
  labels:
    type: local
    app: postgres-person
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/person-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-person-pv-claim
  labels:
    app: postgres-person
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-person
  labels:
    app: postgres-person
spec:
  type: NodePort
  selector:
    app: postgres-person
  ports:
   - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-person
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-person
  template:
    metadata:
      labels:
        app: postgres-person
    spec:
      containers:
        - name: postgres-person-container
          image: library/postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: db-person-map
                key: DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-person-secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-person-map
                key: DB_NAME
          volumeMounts:
            - mountPath: /var/lib/persondb/data
              name: person-db
      volumes:
        - name: person-db
          persistentVolumeClaim:
            claimName: postgres-person-pv-claim